{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "681274cc",
   "metadata": {},
   "outputs": [],
   "source": [
    "## Empresas constituidas:\n",
    "\n",
    "       consta de 16720 y 6 columnas:\n",
    "\n",
    "0   id_const ->\n",
    "        - Es el Id de la tabla un int autoincremental \n",
    "        - Int\n",
    "\n",
    " 1   territorio ->\n",
    "        - Nombra las 19 comunidades autonomas\n",
    "        - String\n",
    "\n",
    " 2   id_tiempo ->\n",
    "        - Muestra año y mes, el mes en digito de 2 numeros, AAAAMM\n",
    "        - Int \n",
    "\n",
    " 3   tipo ->\n",
    "        -Muestra tipo de empresas :\n",
    "                Mercantiles, Es la suma de Sociedad anónima y Sociedad Limitada \n",
    "                Sociedades anónimas,\n",
    "                Sociedades de responsabilidad limitada,\n",
    "                S. Comanditarias y S. Colectivas.\n",
    "        -String\n",
    "        -Categórica con 4 opciones \n",
    "        - Cada categoría tienen 4180 filas, La razón que los valores totales coinciden es porque hay una fila por fecha, independientemente si hay disueltas o no.\n",
    "\n",
    "\n",
    " 4   numero_sociedades ->\n",
    "        -Muestra el numero de sociedades creadas\n",
    "        -Int\n",
    "\n",
    " 5   capital ->\n",
    "        -Capital con el que se constituye la empresas\n",
    "        -Int\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "## Empresas disueltas:\n",
    "\n",
    "       consta de 12539 y 5 columnas\n",
    "\n",
    "0   id_dis ->\n",
    "        - Es el Id de la tabla un int autoincremental \n",
    "        - Int\n",
    "\n",
    "1   territorio ->\n",
    "        - Nombra las 19 comunidades autonomas\n",
    "        - String\n",
    "\n",
    "\n",
    "2   id_tiempo  ->     \n",
    "       - Se representa año y mes , este siempre con dos cifras , es decir ,AAAAMM\n",
    "       - int\n",
    "      \n",
    "\n",
    " 3   razon ->\n",
    "       - corresponde al motivo de la disolucion de las empresas, categorica:\n",
    "              Voluntaria    4180\n",
    "              Por fusión    4180\n",
    "              Otras         4180\n",
    "       * en la api , a la hora de la llamada, existe un motivo mas, Total, que se elimina de la llamada ya que solo es una suma de las demás y da números falseados\n",
    "\n",
    "        - Cada categoría tienen 4180 filas, La razón que los valores totales coinciden es porque hay una fila por fecha, independientemente si hay disueltas o no.\n",
    "\n",
    "       -str  \n",
    "\n",
    " 4   numero_sociedades->\n",
    "       -cantidad de numero de sociedades disueltas\n",
    "       -int\n",
    "\n",
    "       \n",
    "## Sectores IPC:\n",
    "\n",
    "  consta de 14 y 2 columnas\n",
    "\n",
    "0   id_sector ->\n",
    "       - Es el Id que representa la actividad economica\n",
    "                      1,Índice general\n",
    "                     2,Alimentos y bebidas no alcohólicas\n",
    "                     3,Bebidas alcohólicas y tabaco\n",
    "                     4,Vestido y calzado\n",
    "                     5,\"Vivienda, agua, electricidad, gas y otros combustibles\"\n",
    "                     6,\"Muebles, artículos del hogar y artículos para el mantenimiento corriente del hogar\"\n",
    "                     7,Sanidad\n",
    "                     8,Transporte\n",
    "                     9,Información y comunicaciones\n",
    "                     10,\"Actividades recreativas, deporte y cultura\"\n",
    "                     11,Enseñanza\n",
    "                     12,Restaurantes y servicios de alojamiento\n",
    "                     13,Seguros y servicios financieros\n",
    "                     14,\"Cuidado personal, protección social, y bienes y servicios diversos\"\n",
    "\n",
    "       - Int\n",
    "    \n",
    "\n",
    "1   Nombre ->\n",
    "       - Nombrre del sector economico\n",
    "       - String\n",
    "\n",
    "\n",
    "## Territorio:\n",
    "\n",
    "  consta de 20 y 2 columnas\n",
    "\n",
    "0   id_sector ->\n",
    "       - Es el Id que representa numero con el que representamos cada comunidad autonoma, ademas del 1 que es nacional\n",
    "                            1,Nacional\n",
    "                            2,Andalucía\n",
    "                            3,Aragón\n",
    "                            4,\"Asturias, Principado de\"\n",
    "                            5,\"Balears, Illes\"\n",
    "                            6,Canarias\n",
    "                            7,Cantabria\n",
    "                            8,Castilla y León\n",
    "                            9,Castilla - La Mancha\n",
    "                            10,Cataluña\n",
    "                            11,Comunitat Valenciana\n",
    "                            12,Extremadura\n",
    "                            13,Galicia\n",
    "                            14,\"Madrid, Comunidad de\"\n",
    "                            15,\"Murcia, Región de\"\n",
    "                            16,\"Navarra, Comunidad Foral de\"\n",
    "                            17,País Vasco\n",
    "                            18,\"Rioja, La\"\n",
    "                            19,Ceuta\n",
    "                            20,Melilla\n",
    "\n",
    "       - Int\n",
    "    \n",
    "\n",
    "1   Nombre ->\n",
    "       - Nombre de cada comunidad autonoma , mas el total del computo que es nacional \n",
    "       - String\n",
    "\n",
    "\n",
    "## TIEMPO:\n",
    "\n",
    "  consta de 294 y 4 columnas\n",
    "       Representa el periodo de tiempo\n",
    "\n",
    "\n",
    " 0   id_tiempo->  \n",
    "       - Es el Id de la tabla un int autoincremental \n",
    "       - Int\n",
    "      \n",
    " 1   anio ->\n",
    "       - int\n",
    "       - AAAA\n",
    " 2   mes->\n",
    "       -int\n",
    "       - MM\n",
    " 3   nombre_mes->   \n",
    "       -str \n",
    "       -Nombre del mes\n",
    "\n",
    "\n",
    "\n",
    "## TIPO MEDIDA:\n",
    "       consta de 4 filas y 2 columnas\n",
    "\n",
    " 0   id_tipo_medida->  \n",
    "       - Es el Id de la tabla un int autoincremental ,\n",
    "       - Int\n",
    "\n",
    "1   nombre_medida->   \n",
    "       -str \n",
    "       -categorica que representa el tiempo de la comparativa\n",
    "\n",
    "              Índice\n",
    "              Variación mensual\n",
    "              Variación anual\n",
    "              Variación en lo que va de año\n",
    "\n",
    "\n",
    "## IPC:\n",
    "\n",
    "  consta de 311752 y 5 columnas\n",
    "\n",
    "0   id_tiempo s ->\n",
    "       - Es el Id de la tabla un int autoincremental \n",
    "       - Int\n",
    "       - FK tiempo\n",
    "\n",
    "1   id_territorio ->\n",
    "       - el id del territorio que nombra las 19 comunidades autonomas\n",
    "       - Int\n",
    "       - FK territorio\n",
    "\n",
    "\n",
    "2   id_sector    ->     \n",
    "       -Es el Id de la tabla un int autoincremental que representa sector economico de la actividad\n",
    "       - int\n",
    "       - FK sectores_ipc\n",
    "      \n",
    "\n",
    " 3   Id_medida->\n",
    "       - el id del tipo de medida, categorica con 4 categorias:\n",
    "                     1,Índice\n",
    "                     2,Variación mensual\n",
    "                     3,Variación anual\n",
    "                     4,Variación en lo que va de año\n",
    "            - Int\n",
    "            - FK territoriotipo_medida\n",
    "\n",
    " 4   numero_sociedades->\n",
    "       -cantidad de numero de sociedades disueltas\n",
    "       -int\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "TRANSFORMACIONES:\n",
    "\n",
    "1.     TRANS_STRING->\n",
    "\n",
    "    pasamos id's, id_cons, id_tiempo  a string ya que no son matemáticas para hacer operaciones y \n",
    "    tiene mas sentido que las trate como categórico\n",
    "    vamos a cambiar topo de columna string y hacemos funcion en un en punto py. (trans_str) src/transformation\n",
    "\n",
    "            df_empr_const =id_constutias y id_tiempo \n",
    "            df_empr_dis = id_dis, id_tiempo\n",
    "            df_ipc =id_tiempo,id_territorio,id_sector,id_medida\n",
    "            df_sectores_ipc = id_sector\n",
    "            df_territorio = id_territorio\n",
    "            df_tiempo = id_tiempo, anyo, mes\n",
    "            df_tipo_medida = id_medida\n",
    "\n",
    "2.     Normalizacion en texto->\n",
    "    cambiar nombre comunidades, cambiar orden, sin acento, con minuscula y separacion con guion bajo \n",
    "    lo hacemos en un replace , funcion en .py (trans_normal) src/transformation\n",
    "\n",
    "        empresas constituidas - territorio \n",
    "        empresas disueltas - territorio\n",
    "        territorio nombre - territorio \n",
    "\n",
    "\n",
    "\n",
    "\n",
    "3.intEliminar Tipo ['Mercantil']->\n",
    "    es la suma del resto de ctegorias y daria falsos resultados , con ello eliminamos 4180 filas\n",
    "\n",
    "\n",
    "4.     sustituimos el nombre de tipo de empresa->\n",
    "\n",
    "    Sociedad Limitada por las siglas --> S.L., \n",
    "    Sociedad Anonima -->S.A. \n",
    "    S. comanditarias y s. Colectivas -->S.Com/S.C.\n",
    "\n",
    "5.     poner el nombre de las comunidade todos en castellano\n",
    "\n",
    "\n",
    "6.     Guardados nuevos CSV tranformados en  Files / data_proceesed\n",
    "\n",
    "7.     Creamos base de daos con Sql Alchimemy , llamandolo desde un .py (load.py)\n",
    "\n",
    "8.     Creamos .env con los datos y las claves para acceder a MySql desde Python( no se puede observar puesto que esta en GitIgnore)\n",
    "       * para que la base de datos fucione debe crear un doc .env con esta base:\n",
    "\n",
    "       DB_HOST=localhost\n",
    "       DB_PORT=3306\n",
    "       DB_USER=tu_usuario\n",
    "       DB_PASSWORD=tu_contraseña\n",
    "       DB_NAME=nombre_de_tu_base_de_datos\n",
    "\n",
    "\n",
    "9      Crear un GitIgnore para proteger los datos sensibles , metiendo en este el archivo .env"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.14.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
